
== 換気設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 換気設備の計画とは
機械換気で夏期や冬期に開口部（窓）を閉め切った状態においても、建築基準法で求められている0.5回/h以上の換気量を確保し、住宅内の空気環境を安全・快適に保つことを目的とした主として全般換気に関する技術です。
この機械換気に要するエネルギーをいかに節約するかが、また機械換気にともない生じる暖房負荷をいかに低減するかが、換気設備の省エネルギー技術として重要です。

=== 目標レベル
  ☆☆☆☆☆　換気設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　4.6GJ

=== 換気設備の方式の選択
 ・ダクト式第一種換気設備
 ・ダクト式第二種またはダクト式第三種換気設備
 ・壁付け式第一種換気設備
 ・壁付け式第二種換気設備または壁付け式第三種換気設備
 
=== ダクト式第一種換気設備を設置する場合
NOTE: 換気方式の選択により切り替え

 省エネルギー対策の有無と評価の方法
 ・特に省エネルギー対策をしない・評価しない
 ・採用した省エネルギー手法を選択し省エネルギー効果を評価する
        ・ダクト径の大口径化・長さ、曲がりによる圧力損失の低減
        ・高効率機器の導入
 ・比消費電力を入力し省エネルギー効果を評価する
        ・比消費電力　　▲▼  [W/(m3/h)] (小数点以下2桁)
 ・熱交換型換気設備を導入する
        ・夏期・中間期の効率的運転
        ・温度交換効率　　▲▼  [%] (整数)
        ・給気と排気の比率による温度交換効率の補正係数　　　▲▼  [-] (小数点以下2桁))
        ・排気過多時における住宅外皮経由の漏気による温度交換効率の補正係数 　　　▲▼  [-] (小数点以下2桁))

=== ダクト式第二種、第三種換気設備を設置する場合
NOTE: 換気方式の選択により切り替え

 省エネルギー対策の有無と評価の方法
 ・特に省エネルギー対策をしない・評価しない
 ・採用した省エネルギー手法を選択し省エネルギー効果を評価する
        ・ダクト径の大口径化・長さ、曲がりによる圧力損失の低減
        ・高効率機器の導入
 ・温度差利用型ハイブリッド換気の導入
 ・比消費電力を入力し省エネルギー効果を評価する
        ・比消費電力　　0.3▲▼  [W/(m3/h)] (小数点以下2桁)

=== 壁付け式第一種換気設備を設置する場合
NOTE: 換気方式の選択により切り替え

 省エネルギー対策の有無と評価の方法
 ・特に省エネルギー対策をしない・評価しない
 ・ファンと屋外端末の組み合わせを適正化する
 ・比消費電力を入力し省エネルギー効果を評価する
        ・比消費電力　　0.3▲▼  [W/(m3/h)] (小数点以下2桁)
 ・熱交換型換気設備を導入する
        ・温度交換効率　　▲▼  [%] (整数)
        ・給気と排気の比率による温度交換効率の補正係数　　　▲▼  [-] (小数点以下2桁))
        ・排気過多時における住宅外皮経由の漏気による温度交換効率の補正係数 　　　▲▼  [-] (小数点以下2桁))
  
=== 壁付け式第二種、第三種換気設備を設置する場合
NOTE: 換気方式の選択により切り替え

 省エネルギー対策の有無と評価の方法
 ・特に省エネルギー対策をしない・評価しない
 ・ファンと屋外端末の組み合わせを適正化する
 ・比消費電力を入力し省エネルギー効果を評価する
        ・比消費電力　　0.3▲▼  [W/(m3/h)] (小数点以下2桁)

=== 換気回数
 ・0.5回/h
 ・0.7回/h
 ・0.0回/h
 
=== 設計上の配慮・暮らし方等
NOTE: 項目検討中

 ・局所換気と常時全般換気の関係
 ・メンテナンスを意識した計画
 ・外部風などの影響への配慮
 ・給気位置および給気方式の配慮
 ・風量測定の方法と効果
 ・日常清掃への配慮
 ・局所換気への配慮
