
== 換気設備計画マニュアル Bパート：
用語説明（入力時に悩む可能性の高い要素を簡潔に伝える情報）　主担当：中野 →　是永

用語解説
換気：室内に空気がある状態で汚れた空気を排出し、新鮮な外気と入れ替える（改p270）

必要換気量：建築基準法施工令第20条の２第２号による。居室においては0.5回/ｈ。

全般換気：住宅全体を換気すること（居室及び隣接する換気経路上の空間を２４時間換気する）（改p270）

局所換気：住宅の一部（台所、便所、浴室など）を使用時のみ換気すること。燃焼排ガス、臭気、水蒸気などの換気対象物質が場所的に集中して発生する場合に用いられる換気手法。（改p270換気ブックレットp2）

自然換気：換気口により換気する。風力及び内外温度差に起因する浮力により換気量が変動しやすい（改p270）

機械換気：換気ファンなどにより換気する。機械力により強制的に排気、給気を行うため、安定した換気量の確保が可能（改p270）給気と排気の両方、またはどちらかにファンが必要（ブックレットp3）。組み合わせにより、第一種～第三種の3種類の方式に大別される（ブックレットp3）

温度差換気：室内温度と外気温度の差が大きい冬期には、温度差による煙突効果（暖かい空気が上昇する力）による自然換気を行い、温度差が小さい夏期・中間期には機械換気設備を利用する換気(換気ブックレットp6)

機械換気：

ダクト式換気システム：ダクトを用いることで意図した場所への給気又は意図した場所からの排気を行うこと。

壁付け式換気システム：

ハイブリッド換気：

圧力損失：流体が機械装置などを通過する際の単位時間単位流量あたりのエネルギー損失である。摩擦損失とも呼ばれる。損失は装置内の抵抗に打ち勝つためにその分だけエネルギーを消費することによる。（wikipedia）。圧力損失が小さいほうが省エネルギーである。

高効率ファン：エネルギー効率の高いファン（改p279）

熱交換換気：熱交換素子の狭い部分を空気が通過するため、一般の換気設備より換気動力が増加します。しかし排気の際に屋外に捨てられる熱を回収することができるため、主として暖房エネルギーを抑制することができます（改p264）。

比消費電力：換気設備のエネルギー効率を判断する指標。値が小さいほうが省エネルギー性能が高い。比消費電力（W(㎥/h)）＝消費電力÷風量

端末部材：屋外から外気の取り入れ口、屋外へ室内空気の排出口に取り付ける部材。圧力損失の小さいものを選定することが重要（改p276,280）。

気密性能：建物に存在する隙間の程度を表したもの。専用の測定器で計測し、相当隙間面積C値という指標で表されます(改p73)。

換気経路：給気から排気に至る空気の流れのこと。排出された空気が再度外気として入ってくるのを防ぐ必要がある。（改p270）

設計風量：

機外圧力：

交流モーター(ACモーター)：

直流モーター（DCモーター）：

必要有効開口面積：

プロペラファン：

シロッコファン：

ターボファン：

同時給排気型：

気密シャッター：換気停止時の隙間風対策。(改p277)

輻流型：壁面に沿って吸気が放射状に拡散する形状のもの(改p277、図９)

