
== 換気設備計画マニュアル Dパート：
要素技術に関連する留意点・注意事項等（換気扇のメンテナンスについて等）　主担当：辻

== 設計上の配慮事項・暮らし方等（Dパート：Web上のヘルプ）

==== 気密性能と換気の関係
　気密性能が確保された住宅では、台所などの風量の大きな局所換気で全般換気を乱さないよう、同時給排気型の換気扇を用いるか、専用の給気口を設置する必要があります。
　第三種全般換気は、気密性能によって隙間からの空気進入が増えることがあるため、気密性能の向上に配慮します。また、計画換気のために、局所換気設備は停止時にシャッターを閉鎖できる機器を選択するなどの工夫が必要です。

==== メンテナンスを意識した計画
　常時換気設備は、メンテナンスがしやすい位置に設置し、フィルターや羽根の点検・清掃を容易に行うことができる機種を選定します。また、屋外端末（外気取り入れ口）についてもメンテナンスができる場所に設置することが基本です。メンテナンスを怠ると適切な風量が得られない場合があります。住まい手に対して定期的な清掃が必要であることを伝えることも徹底します。

==== 給気位置および給気方式の配慮
　居住域に直接冷気が達することを防ぐために、輻流型（壁面にそって給気が放射状に拡散する形状のもの）等の採用を検討します。




== Eパート：フルの情報（要素技術をじっくり理解するための情報）

==== 局所換気と常時全般換気の関係
　外皮の断熱性が確保された住宅における台所の局所換気扇には、居室の温熱環境や他の換気経路を乱すことのないよう、同時給排気型の換気扇を用いるか、専用の給気口を設置する必要があります。また、台所の換気扇には、少ない排気風量で調理にともなう汚染空気を効率的に排出することが可能な（排気捕集性能の高い）機器を選択すると、電力消費や冷暖房エネルギー削減の点で有利になります。
　第三種換気で全般換気を行う場合、住宅の気密性能によっては、給気口よりも隙間からの空気の進入が多くなります。計画した給気口から居室にバランスよい給気を確保するためには、外皮の性能以外に、全般換気に供しない局所換気設備には停止時にシャッターを閉鎖できるしくみの機器を選択するなどの工夫が必要です。

==== メンテナンスを意識した計画
　①本体
常時換気設備は、メンテナンスがしやすい位置に設置することが望ましいといえます。図6、図7 は壁に設置が可能な換気システムの例で、天井裏に埋設しないため、フィルターや羽根の点検・清掃を容易に行うことができます。こうした対応が難しい場合でも、点検やメンテナンスを容易に行えるような工夫は不可欠です。

TIP: 温暖地版P277　図6、図7

天井裏などに隠蔽されるタイプの換気機器には、メンテナンスが困難であること、住まい手がフィルター等の汚れを容易に認識できないことなどの問題点があり、今後の改善課題であるといえます。
メンテナンスについて、設計段階での対応策としては、以下の3 つが考えられます。
a. フィルターのついているファンは定期的にフィルターの清掃が、フィルターの付いていないファンは定期的に送風ファンの羽根の清掃が必要であり、いずれの場合でも日常の清掃に配慮した機器の選択を検討する。
b. 清掃が容易となるように、換気装置を納戸や小屋裏などの収納空間に露出させて設置したり、換気ユニット本体を床上に設置するなどの工夫をする。
c. 住まい手に対して定期的な清掃が必要であることを伝えることを徹底する。

②端末部材
また、忘れがちな屋外端末（外気取り入れ口）についてもメンテナンスへの配慮が必要です。外気取り入れ口には防虫網が設置されていることが多く、防虫網も定期的にメンテナンスを行わないと、換気能力が低下します。2 階においては、バルコニーなどから清掃できる場所に設置することが基本です（図8）。また、1 階においては、地上からは容易に届かない場所に設置する場合が多くなり、脚立などを用いて清掃できるよう配慮しておく必要があります。
端末部材には防虫網を設置せずに、機器の側にフィルターを設置する場合にも、メンテナンスの容易性を検討する必要があります。この場合には、外壁部分に防鳥網を設置し、ダクト内への鳥の侵入を防ぐ必要があります。

TIP: 温暖地版P278　図8

==== 外部風などの影響への配慮
　壁付け式換気扇（パイプ用ファン）のうち、局所換気用に設計された機種には、電動式の気密シャッターが付属しているものがあります。気密シャッターは、換気停止時の隙間風対策として用意されていますが、開放している時間は電力消費が生じています。常時運転を想定する場合は、電動気密シャッターの付属していない機種を選択することにより、省エネルギーをはかることができます。ただし、冬期の換気風量低減のため、運転を停止させる場合も想定し、電動気密シャッター付属の機種を選ぶこともあります。
年間を通じて外部風が強く、台風の到来も多い地域では、深型や耐外風タイプの屋外フードやダンパー付きの換気口（図9）を用いることで、強風が吹きつけたときでも、比較的安定した風量に制御することができます。また、海に面する地域で、とくに潮風の強い場所では、塩害対策の施された屋外端末部材を用いることで、錆の発生を抑えることができます。

TIP: 温暖地版P278　図9

==== 給気位置および給気方式の配慮
　居住域に直接冷気が達することを防ぐために、輻流型（壁面にそって給気が放射状に拡散する形状のもの）等の採用を検討します（図10）。
 
TIP: 温暖地版P278　図10

==== 風量測定の方法と効果
　計画換気で最も重要なのは計画された換気量や換気性能が確実に得られることです。そのため、施工後に換気システムの風量を検証することは極めて重要です。
換気システムの現場での風量測定には比較的入手が容易なフード付風量計が利用される例が多いです。フード付風量計は「フード」を有する風量測定器の呼称で、図11、図12 のように室内あるいは室外の換気システム端末部材（屋内吸込み端末や吹出し端末、屋外フードなど）に測定器を当てて、風量を測定するものです。
　風量測定は計画風量が得られていることの確認のみでなく、各端末部材における風量のバランス調整の際や、計画風量が得られていない場合の原因を推定するためにも有用です。各端末部材での測定を行うことで、風量が少ない端末の系統についての問題や、全体の風量が少ない場合における主ダクトやファンユニット本体についての問題を推定することができます。
　また、風量測定を行った結果、計画風量以上であった場合は、計画風量となるように調整することで、消費電力や換気負荷が低減され、より省エネ効果が得られます。
 
TIP: 温暖地版P279　図11、図12
 
==== 日常清掃への配慮
　1）　壁付け式換気扇の汚れ付着による能力低下への配慮
2年間にわたり便所で使用した図13 の状態での風量は初期の75％程度でした。汚れが付着して換気能力が下がることは、換気量の低下に加え、エネルギーを無駄に消費していることになります。省エネルギーを実現するためには、常にメンテナンスを行い、初期に近い状態で運転することが必要となります。フィルターを設置した場合でも、メンテナンスを怠るとフィルターが目詰まりを起こし、計画された換気量が得られなくなります。

TIP: 温暖地版P280　図13

　2）　メンテナンスの容易性への配慮
一般ユーザーが清掃などのメンテナンスが容易にできる機器を選択することで、長期間の性能を維持することが可能となります（図14、図15）。
　図14 は、壁付け用換気扇のフィルターの掃除の様子です。吸込み口にフィルターが設けられている機器を選択することで、羽根の汚損や屋外フードの防虫網の目詰まりを低減し、風量低下を抑制することができます。フィルター面に付着した埃などを掃除機で吸い取るだけで完了します。
　図15 は、本体の分解が容易な機種の例です。この場合、羽根についたホコリまで清掃が可能となります。工具なしで羽根まで取り外すことができる機器もあります。

TIP: 温暖地版P280　図14、図15

　清掃等のメンテナンスがなかなか実施できない住まい手のためには、そもそも汚れが付きにくく、清掃の頻度が少なくてすむタイプを選択することができます。例えば、ファンの部分などに汚れが付きにくいコーティングを施し、汚れの付着を約5 分の1 程度まで低減したものがあります。図は10 年後を想定したシロッコファンへの埃付着実験の結果比較です。左側はコーティングなしで羽部分に多量の埃が付着しています。右はコーティングありで、埃の付着が少なくなっています。
 
TIP: 改修版P278　図a

　3）　ダクト式換気システムの汚れと対策
一般的に住宅用24 時間全般換気システムのメンテナンスは、居住者が行うフィルター清掃などの軽微なメンテナンスと、モーター交換やダクト清掃など専門業者が行う大がかりなメンテナンスがあります。例えば、市販されている多くのダクト式第一種熱交換型換気システムは、図16 のように換気ユニット内にフィルターや防虫対策用部材が設置されており、外気導入時に含まれる虫や埃、花粉などを除去する方法を採用しています。この方式の場合、清掃を怠ると図の様にフィルター全面に埃が滞積したり、防虫対策部材に虫が溜まり、目詰まりを起こしてしまい、計画した換気量が得られなくなりますので定期的なメンテナンスを行って下さい。（通常メンテ
ナンスができない外部フードには防虫対策用網等を付けないで下さい。目詰まりをおこし計画した換気量が得られなくなります。）
また、室内端末部材の近傍の給排気を阻害するような位置に家具などを置かないようにしてください。メンテナンスを怠るのと同様に、計画した換気量が得られなくなります。

TIP: 温暖地版P281　図16
 
